<a href="https://colab.research.google.com/github/CoolSoldier/Pythorch-Tutorial/blob/main/Tensors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
import numpy as np

# Lists


In [4]:
my_list = [[1,2,3,4], [5,6,7,8]]
my_list

[[1, 2, 3, 4], [5, 6, 7, 8]]

#NUMPY AARAYS

In [5]:
np1 = np.random.rand(3,4)

array([[0.23257228, 0.32215   , 0.32052457, 0.54384242],
       [0.32664554, 0.87699773, 0.28788231, 0.77881192],
       [0.27820779, 0.39209306, 0.17440199, 0.93081903]])

In [6]:
np1.dtype

dtype('float64')

# Tensors

In [8]:
tensor_2d = torch.randn(3,4)
tensor_2d

tensor([[ 0.0939,  0.1341, -1.2274, -0.1463],
        [-0.0611,  1.1086, -1.4109, -0.0442],
        [ 1.3940,  1.5237,  0.0959,  0.3164]])

In [9]:
tensor_2d.dtype

torch.float32

In [11]:
tensor_3d = torch.zeros(2,3,4)
tensor_3d

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [14]:
## Create tensor out of numpy array
my_tensor = torch.tensor(np1)
my_tensor

tensor([[0.2326, 0.3221, 0.3205, 0.5438],
        [0.3266, 0.8770, 0.2879, 0.7788],
        [0.2782, 0.3921, 0.1744, 0.9308]], dtype=torch.float64)